# Generated by Django 5.0.7 on 2024-09-09 22:07
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_post_tags'),
    ]

    operations = [
        TrigramExtension()
    ]
